services:
  CacheInterface:
    class: Chapi\Component\Cache\DoctrineCache
    arguments:
      - "@ExternalDoctrineCacheInterface"
      - "%repository_dir%.%chronos_url%"

  ExternalDoctrineCacheInterface:
    class: Doctrine\Common\Cache\FilesystemCache
    arguments: ["%cache_dir%"]