services:
  HttpClientGuzzle:
    class: Chapi\Component\Http\HttpGuzzlClient
    arguments:
      - "@ExternalGuzzleClientInterface"
      - "@HttpAuthEntity"

  ExternalGuzzleClientInterface:
    class: GuzzleHttp\Client
    arguments:
      - base_url: "%chronos_url%"

  HttpAuthEntity:
    class: Chapi\Entity\Http\AuthEntity
    arguments:
      - "%chronos_http_username%"
      - "%chronos_http_password%"