services:
  HttpClientGuzzle:
    class: Chapi\Component\Http\HttpGuzzlClient
    arguments:
      - "@ExternalGuzzleClientInterface"
      -
        username: "%chronos_http_username%"
        password: "%chronos_http_password%"

  ExternalGuzzleClientInterface:
    class: GuzzleHttp\Client
    arguments:
      - base_url: "%chronos_url%"