language: php

sudo: false

cache:
  directories:
    - $HOME/.chapi/cache

addons:
  apt_packages:
    - parallel

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm-nightly

before_script:
  - git config --global user.name travis-ci
  - git config --global user.email travis@example.com
  - composer install

script:
    - ls -d test/unit/* | parallel --gnu --keep-order 'echo "Running {} tests"; ./vendor/bin/phpunit -c test/phpunit.xml --colors=always {} || (echo -e "\e[41mFAILED\e[0m {}" && $(exit 1));'

git:
  depth: 5