language: php

cache:
  directories:
    - $HOME/.chapi/cache

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true

before_script:
  - git config --global user.name travis-ci
  - git config --global user.email travis@example.com
  - composer self-update
  - composer install
  - cd test/

