services:
  ChronosStoreJobBusinessCase:
    class: Chapi\BusinessCase\JobManagement\ChronosStoreJobBusinessCase
    arguments:
      - "@JobIndexServiceInterface"
      - "@JobRepositoryChronos"
      - "@JobRepositoryFileSystemChronos"
      - "@ChronosJobComparisionBusinessCase"
      - "@JobDependencyServiceInterface"
      - "@LoggerInterface"
