services:
  ChronosHttpClientGuzzle:
    class: Chapi\Component\Http\HttpGuzzleClient
    arguments:
      - "@ExternalChronosGuzzleClient"
      - "@ChronosHttpAuthEntity"

  ExternalChronosGuzzleClient:
    class: GuzzleHttp\Client
    arguments:
      - base_uri: "%chronos_url%"

  ChronosHttpAuthEntity:
    class: Chapi\Entity\Http\AuthEntity
    arguments:
      - "%chronos_http_username%"
      - "%chronos_http_password%"
