services:
  MarathonJobComparisionBusinessCase:
    class: Chapi\BusinessCase\Comparison\MarathonJobComparisonBusinessCase
    arguments:
      - "@JobRepositoryFileSystemMarathon"
      - "@JobRepositoryMarathon"
      - "@DiffCompareInterface"
