services:
  JobRepositoryChronos:
    class: Chapi\Service\JobRepository\JobRepositoryChronos
    arguments:
      - "@ApiClientInterface"
      - "@CacheInterface"
      - "@JobEntityValidatorServiceInterface"

  JobRepositoryFileSystem:
    class: Chapi\Service\JobRepository\JobRepositoryFileSystem
    arguments:
      - "@ExternalFileSystemService"
      - "@CacheInterface"
      - "%repository_dir%"

  JobEntityValidatorServiceInterface:
    class: Chapi\Service\JobRepository\JobEntityValidatorService
    arguments:
      - "@DatePeriodFactoryInterface"

  ExternalFileSystemService:
    class: \Symfony\Component\Filesystem\Filesystem