services:
  JobRepositoryChronos:
    class: Chapi\Service\JobRepository\JobRepository
    arguments:
      - "@JobRepositoryBridgeChronos"

  JobRepositoryFileSystem:
    class: Chapi\Service\JobRepository\JobRepository
    arguments:
      - "@JobRepositoryBridgeFileSystem"

  JobRepositoryBridgeChronos:
    class: Chapi\Service\JobRepository\BridgeChronos
    arguments:
      - "@ApiClientInterface"
      - "@CacheInterface"
      - "@JobValidatorServiceInterface"
      - "@LoggerInterface"

  JobRepositoryBridgeFileSystem:
    class: Chapi\Service\JobRepository\BridgeFileSystem
    arguments:
      - "@ExternalFileSystemService"
      - "@CacheInterface"
      - "%repository_dir%"

  JobValidatorServiceInterface:
    class: Chapi\Service\JobRepository\JobValidatorService
    arguments:
      - "@DatePeriodFactoryInterface"

  ExternalFileSystemService:
    class: \Symfony\Component\Filesystem\Filesystem