services:
  JobComparisonInterface:
    class: Chapi\BusinessCase\Comparison\JobComparisonBusinessCase
    arguments:
      - "@JobRepositoryFileSystem"
      - "@JobRepositoryChronos"
      - "@DiffCompareInterface"
      - "@DatePeriodFactoryInterface"