services:
  StoreJobBusinessCaseInterface:
    class: Chapi\BusinessCase\JobManagement\StoreJobBusinessCase
    arguments:
      - "@JobIndexServiceInterface"
      - "@JobRepositoryChronos"
      - "@JobRepositoryFileSystem"
      - "@JobComparisonInterface"
      - "@LoggerInterface"