services:
  StoreJobBusinessCaseFactoryInterface:
    class: Chapi\BusinessCase\JobManagement\StoreJobBusinessCaseFactory
    calls:
      - [addBusinesCase, ["@ChronosStoreJobBusinessCase"]]
      - [addBusinesCase, ["@MarathonStoreBusinessCase"]]
