services:
  JobComparisonInterface:
    class: Chapi\BusinessCase\Comparison\CompositeJobComparisonBusinessCase
    calls:
      - [addComparisonCases, ["@ChronosJobComparisionBusinessCase"]]
      - [addComparisonCases, ["@MarathonJobComparisionBusinessCase"]]
